name: 'Check Sphinx Docs'
description: 'Ensures that Sphinx docs can be built'

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v3
  - uses: ammaraskar/sphinx-action@master
    with:
      docs-folder: "docs/"
  