name: 'Check manifest'
description: 'Check Python package manifest'


runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install check-manifest
    - name: Check Manifest
      shell: bash
      run: check-manifest
