name: Python test workflow

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      python-version:
        required: true
        type: string

jobs:
  python-tests:
    runs-on: ${{ inputs.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install tox
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox
    - name: Run tests
      run: tox
